// <auto-generated> This file is generated by AudioTagsGenerator. Do not edit manually!
namespace Scripts.Services.Audio.AudioSystem.Configs
{
    public static class AudioTags
    {
        // Groups
        public const string Group_Gameplay = "Gameplay";
        public const string Group_MainMusic = "MainMusic";

        // Sounds
        public const string Sound_Bomb = "Bomb";
        public const string Sound_Match = "Match";
        public const string Sound_Theme_01 = "Theme_01";
    }
}