using UnityEngine;

namespace Project.Scripts.Configs.Battle
{
    [CreateAssetMenu(fileName = "MatchDamageConfig", menuName = "Configs/Battle/Match Damage Config")]
    public class MatchDamageConfig : ScriptableObject
    {
        [Header("Base Match Damage")]
        [Tooltip("Damage dealt by a match of 3 tiles")]
        [SerializeField] private int _match3Damage = 10;

        [Tooltip("Damage dealt by a match of 4 tiles")]
        [SerializeField] private int _match4Damage = 18;

        [Tooltip("Damage dealt by a match of 5+ tiles")]
        [SerializeField] private int _match5PlusDamage = 30;

        [Tooltip("Additional damage per tile beyond 5 in a single match")]
        [SerializeField] private int _extraTileDamage = 5;

        [Header("Shape Bonuses")]
        [Tooltip("Flat damage bonus for L-shape matches")]
        [SerializeField] private int _lShapeBonus = 15;

        [Tooltip("Flat damage bonus for T-shape matches")]
        [SerializeField] private int _tShapeBonus = 25;

        [Header("Wave Multipliers")]
        [Tooltip("Cascade multiplier increase per level. Cascade 1 = x1.0, cascade 2 = x(1.0 + step), etc.")]
        [SerializeField] private float _cascadeMultiplierStep = 0.2f;

        [Tooltip("Bonus multiplier applied when 2 or more matches occur in a single wave")]
        [SerializeField] private float _multiMatchBonus = 0.2f;

        [Header("Bomb")]
        [Tooltip("Damage per tile destroyed by a bomb")]
        [SerializeField] private int _bombDamagePerTile = 3;

        [Header("Energy")]
        [Tooltip("Energy generated by a match of 3 tiles")]
        [SerializeField] private int _match3Energy = 1;

        [Tooltip("Energy generated by a match of 4 tiles")]
        [SerializeField] private int _match4Energy = 3;

        [Tooltip("Energy generated by a match of 5+ tiles")]
        [SerializeField] private int _match5PlusEnergy = 5;


        public int Match3Damage => _match3Damage;
        public int Match4Damage => _match4Damage;
        public int Match5PlusDamage => _match5PlusDamage;
        public int ExtraTileDamage => _extraTileDamage;
        public int LShapeBonus => _lShapeBonus;
        public int TShapeBonus => _tShapeBonus;
        public float CascadeMultiplierStep => _cascadeMultiplierStep;
        public float MultiMatchBonus => _multiMatchBonus;
        public int BombDamagePerTile => _bombDamagePerTile;
        public int Match3Energy => _match3Energy;
        public int Match4Energy => _match4Energy;
        public int Match5PlusEnergy => _match5PlusEnergy;
    }
}