using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Project.Scripts.Services.Audio.AudioSystem.Configs
{
#if UNITY_EDITOR
    public class AudioTagsGenerator
    {
        private const string OutputPath = "Assets/Scripts/CodeGen/AudioTags.cs";

        [MenuItem("Tools/CodeGen/Generate AudioTags")]
        public static void GenerateAudioTagsFromMenu()
        {
            GenerateAudioTags();
        }
        
        public static void GenerateAudioTags()
        {
            var musicConfigGuids = AssetDatabase.FindAssets("t:AudioMusicConfig");
            var sfxConfigGuids = AssetDatabase.FindAssets("t:AudioSFXConfig");
            var allGroups = new List<AudioGroupData>();

            for (var i = 0; i < musicConfigGuids.Length; i++)
            {
                var guid = musicConfigGuids[i];
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var config = AssetDatabase.LoadAssetAtPath<AudioMusicConfig>(path);
                if (config)
                    allGroups.AddRange(config.Groups);
            }

            for (var i = 0; i < sfxConfigGuids.Length; i++)
            {
                var guid = sfxConfigGuids[i];
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var config = AssetDatabase.LoadAssetAtPath<AudioSFXConfig>(path);
                if (config)
                    allGroups.AddRange(config.Groups);
            }

            if (allGroups.Count == 0)
            {
                Debug.LogError("No Audio configs found!");
                return;
            }

            var groupTags = new HashSet<string>();
            var soundTags = new HashSet<string>();

            for (var i = 0; i < allGroups.Count; i++)
            {
                var group = allGroups[i];
                if (false == string.IsNullOrEmpty(group.GroupTag))
                    if (false == groupTags.Add(group.GroupTag))
                        Debug.LogError($"Duplicate group tag found: {group.GroupTag}");

                for (var j = 0; j < group.Clips.Count; j++)
                {
                    var clip = group.Clips[j];
                    if (false == string.IsNullOrEmpty(clip.Tag))
                        if (false == soundTags.Add(clip.Tag))
                            Debug.LogError($"Duplicate sound tag found: {clip.Tag}");
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> This file is generated by AudioTagsGenerator. Do not edit manually!");
            sb.AppendLine("namespace Scripts.Services.Audio.AudioSystem.Configs");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AudioTags");
            sb.AppendLine("    {");
            sb.AppendLine("        // Groups");
            foreach (var tag in groupTags.OrderBy(t => t))
            {
                var constName = SanitizeName(tag, "Group_");
                sb.AppendLine($"        public const string {constName} = \"{tag}\";");
            }

            sb.AppendLine();
            sb.AppendLine("        // Sounds");
            foreach (var tag in soundTags.OrderBy(t => t))
            {
                var constName = SanitizeName(tag, "Sound_");
                sb.AppendLine($"        public const string {constName} = \"{tag}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath));
            File.WriteAllText(OutputPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"AudioTags.cs generated at {OutputPath} with {groupTags.Count} groups and {soundTags.Count} sounds.");
        }

        private static string SanitizeName(string original, string prefix)
        {
            var sanitized = new string(original
                .Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_')
                .ToArray());

            if (string.IsNullOrEmpty(sanitized)) 
                sanitized = "InvalidTag";
            if (char.IsDigit(sanitized[0])) 
                sanitized = "X" + sanitized;

            sanitized = prefix + char.ToUpper(sanitized[0]) + sanitized.Substring(1);
            return sanitized;
        }
    }

    [CustomEditor(typeof(AudioMusicConfig))]
    public class AudioMusicConfigEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            if (GUILayout.Button("Generate Audio Tags")) 
                AudioTagsGenerator.GenerateAudioTags();
        }
    }

    [CustomEditor(typeof(AudioSFXConfig))]
    public class AudioSFXConfigEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            if (GUILayout.Button("Generate Audio Tags")) 
                AudioTagsGenerator.GenerateAudioTags();
        }
    }
#endif
}